// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFBmwrwh2EczdVVgxaMboxj7y2UcmsjA',
    appId: '1:743895891329:web:48f454ae170a498eedbc80',
    messagingSenderId: '743895891329',
    projectId: 'chatapp-c7567',
    authDomain: 'chatapp-c7567.firebaseapp.com',
    storageBucket: 'chatapp-c7567.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCju0436ZmS686S425z3svFXji6sOeRt-s',
    appId: '1:743895891329:android:0fd9b49f5641a6e5edbc80',
    messagingSenderId: '743895891329',
    projectId: 'chatapp-c7567',
    storageBucket: 'chatapp-c7567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJhfUVu3SV33Q5MgUNJW9UTzyvbqEy6E',
    appId: '1:743895891329:ios:8272f01d91df110eedbc80',
    messagingSenderId: '743895891329',
    projectId: 'chatapp-c7567',
    storageBucket: 'chatapp-c7567.appspot.com',
    androidClientId: '743895891329-2tru6csroqlo55j26pothki5k97ipcn3.apps.googleusercontent.com',
    iosClientId: '743895891329-3s7o72makiol5qg6ioopad1h7cbnjna0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJhfUVu3SV33Q5MgUNJW9UTzyvbqEy6E',
    appId: '1:743895891329:ios:8272f01d91df110eedbc80',
    messagingSenderId: '743895891329',
    projectId: 'chatapp-c7567',
    storageBucket: 'chatapp-c7567.appspot.com',
    androidClientId: '743895891329-2tru6csroqlo55j26pothki5k97ipcn3.apps.googleusercontent.com',
    iosClientId: '743895891329-3s7o72makiol5qg6ioopad1h7cbnjna0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
